steps:
  - name: 'ubuntu'
    args: ['bash', './buildscripts/create_json_auth_file.sh']
    env:
     - 'GOOGLE_APPLICATION_CREDENTIALS_CONTENT=${_GOOGLE_APPLICATION_CREDENTIALS_CONTENT}'
     - 'GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}'
  - name: maven:3.6.1-jdk-12
    entrypoint: 'mvn'
    args: ['clean', 'install']
    env:
     - 'GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/sunnyvale-academy/helidon_helloworld:$TAG_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sunnyvale-academy/helidon_helloworld:$TAG_NAME']