steps:
  - name: 'ubuntu'
    args: ['bash', './buildscripts/create_json_auth_file.sh']
    env:
     - 'GOOGLE_APPLICATION_CREDENTIALS_CONTENT=${_GOOGLE_APPLICATION_CREDENTIALS_CONTENT}'
     - 'GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.native', '-t', 'gcr.io/sny-prg-dvs-01-01-00/helidon_helloworld:$TAG_NAME', '.']
    env:
     - 'GOOGLE_APPLICATION_CREDENTIALS=${_GOOGLE_APPLICATION_CREDENTIALS}'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/sny-prg-dvs-01-01-00/helidon_helloworld:$TAG_NAME']